#!/usr/bin/env bash
# a bash script that installs nginx web server
# returns a page that contains the string "Hello World!"
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
