#!/usr/bin/env bash
# a bash script that installs nginx web server and configures it

sudo apt-get update
sudo apt-get -y install nginx

# configures the web server to return "Hello World" upon GET request
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# configures nginx redirection
replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/omobolaji001 permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-available/default

# creates error page and add a redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
replace_string="listen [::]:80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen [::]:80 default_server;/$replace_string/" /etc/nginx/sites-available/default

# restarts nginx
sudo service nginx restart
