#!/usr/bin/env bash
# a bash script that installs nginx web server
# returns a page that contains the string "Hello World!"
# configures nginx redirection
# creates error page and add a redirect for error 404

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/omobolaji001 permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404.html
replace_string="listen [::]:80 default server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen [::]:80 default server;/$replace_string/" /etc/nginx/sites-available/default

sudo service nginx restart
