#!/usr/bin/env bash

# configures nginx to run as `nginx` user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# configures nginx to listen on all active IPs on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# gives read and write permissions of `nginx.conf` to owner
chmod 644 /etc/nginx/nginx.conf

# kill apache2 to prevent it from interfering with nginx
pkill apache2

# start nginx service with the new nginx user
sudo -u nginx service nginx start
